services:
  - type: web
    name: tokyo-marui-search
    runtime: python

    buildCommand: |
      apt-get update
      apt-get install -y wget unzip xvfb gnupg
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      apt-get update
      apt-get install -y google-chrome-stable
      pip install -r requirements.txt

    startCommand: gunicorn app:app
